-- 180 LinkedIn topics transcribed from six distinct user-supplied lists.
-- Reapplying this seed never replaces edited notes or publication statuses.
insert into public.cso_content_topics (id, platform, category, title, status, note)
values
  ('linkedin-topic-1', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Ile naprawdę kosztuje miesięczna księgowość spółki z o.o. i skąd biorą się różnice między ofertami biur?', 'pomysl', ''),
  ('linkedin-topic-2', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Od czego bardziej zależy cena pełnej księgowości: od liczby faktur czy od stopnia skomplikowania działalności?', 'pomysl', ''),
  ('linkedin-topic-3', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Dlaczego dwie spółki mające po 100 dokumentów miesięcznie mogą płacić zupełnie inne kwoty za księgowość?', 'pomysl', ''),
  ('linkedin-topic-4', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Jakie opłaty dodatkowe mogą pojawić się poza miesięcznym abonamentem biura rachunkowego?', 'pomysl', ''),
  ('linkedin-topic-5', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Czy sporządzenie rocznego sprawozdania finansowego powinno być w cenie miesięcznej obsługi?', 'pomysl', ''),
  ('linkedin-topic-6', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Czy obsługa KSeF powinna zwiększać cenę księgowości spółki?', 'pomysl', ''),
  ('linkedin-topic-7', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] O ile transakcje zagraniczne i rozliczenia walutowe mogą zwiększyć koszt księgowości?', 'pomysl', ''),
  ('linkedin-topic-8', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Dlaczego księgowość e-commerce kosztuje często więcej niż księgowość spółki usługowej?', 'pomysl', ''),
  ('linkedin-topic-9', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Ile kosztuje obsługa kadrowo-płacowa pracowników poza prowadzeniem pełnych ksiąg?', 'pomysl', ''),
  ('linkedin-topic-10', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Czy miesięczne raporty dla zarządu powinny być częścią księgowości, czy osobno płatną usługą?', 'pomysl', ''),
  ('linkedin-topic-11', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Ile może kosztować przejęcie księgowości spółki od poprzedniego biura?', 'pomysl', ''),
  ('linkedin-topic-12', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Kto ponosi koszt poprawienia błędów pozostawionych przez poprzednie biuro rachunkowe?', 'pomysl', ''),
  ('linkedin-topic-13', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Czy konsultacje podatkowe powinny być zawarte w abonamencie księgowym?', 'pomysl', ''),
  ('linkedin-topic-14', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Jak zmienia się cena księgowości, kiedy firma szybko zwiększa liczbę dokumentów?', 'pomysl', ''),
  ('linkedin-topic-15', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Kiedy bardziej opłaca się zatrudnić księgową na etat niż korzystać z zewnętrznego biura?', 'pomysl', ''),
  ('linkedin-topic-16', 'linkedin', 'Ceny i koszty', '[Sp. z o.o.] Ile naprawdę może kosztować firmę bardzo tania księgowość, jeżeli nie obejmuje kontroli, raportów i bieżącego kontaktu?', 'pomysl', ''),
  ('linkedin-topic-17', 'linkedin', 'Ceny i koszty', '[NGO] Ile kosztuje pełna księgowość fundacji albo stowarzyszenia?', 'pomysl', ''),
  ('linkedin-topic-18', 'linkedin', 'Ceny i koszty', '[NGO] Ile kosztuje prowadzenie UEPIK i kiedy jest rzeczywiście tańsze od pełnych ksiąg?', 'pomysl', ''),
  ('linkedin-topic-19', 'linkedin', 'Ceny i koszty', '[NGO] Czy rozliczanie dotacji i projektów powinno być dodatkowo płatne?', 'pomysl', ''),
  ('linkedin-topic-20', 'linkedin', 'Ceny i koszty', '[NGO] Ile kosztuje przygotowywanie dodatkowych zestawień wymaganych przez grantodawców?', 'pomysl', ''),
  ('linkedin-topic-21', 'linkedin', 'Ceny i koszty', '[Klub sportowy] Ile kosztuje księgowość większego klubu sportowego i co najbardziej wpływa na cenę?', 'pomysl', ''),
  ('linkedin-topic-22', 'linkedin', 'Ceny i koszty', '[Klub sportowy] Czy dotacje, sponsorzy, składki członkowskie i kilka źródeł finansowania podnoszą koszt obsługi księgowej?', 'pomysl', ''),
  ('linkedin-topic-23', 'linkedin', 'Ceny i koszty', '[NGO] Czy księgowość organizacji posiadającej status OPP musi kosztować więcej?', 'pomysl', ''),
  ('linkedin-topic-24', 'linkedin', 'Ceny i koszty', '[NGO] Czy fundacja albo stowarzyszenie powinno płacić pełną stawkę również w miesiącach, w których praktycznie nie ma dokumentów?', 'pomysl', ''),
  ('linkedin-topic-25', 'linkedin', 'Ceny i koszty', '[JDG] Ile powinna kosztować księgowość jednoosobowej działalności w 2026 roku?', 'pomysl', ''),
  ('linkedin-topic-26', 'linkedin', 'Ceny i koszty', '[JDG] Co jest tańsze w praktyce: biuro rachunkowe czy samodzielna księgowość online?', 'pomysl', ''),
  ('linkedin-topic-27', 'linkedin', 'Ceny i koszty', '[JDG] O ile VAT zwiększa koszt obsługi księgowej JDG?', 'pomysl', ''),
  ('linkedin-topic-28', 'linkedin', 'Ceny i koszty', '[JDG] Dlaczego faktury zagraniczne mogą zwiększyć cenę księgowości nawet w małej działalności?', 'pomysl', ''),
  ('linkedin-topic-29', 'linkedin', 'Ceny i koszty', '[Wspólne] Kiedy najtańszy pakiet księgowy przestaje być najtańszym rozwiązaniem?', 'pomysl', ''),
  ('linkedin-topic-30', 'linkedin', 'Ceny i koszty', '[Wspólne] Jak policzyć rzeczywisty roczny koszt księgowości, a nie tylko miesięczny abonament?', 'pomysl', ''),
  ('linkedin-topic-31', 'linkedin', 'Problemy', '[Sp. z o.o.] Po czym poznać, że problemem nie jest pojedynczy błąd księgowej, ale cały sposób współpracy z biurem?', 'pomysl', ''),
  ('linkedin-topic-32', 'linkedin', 'Problemy', '[Sp. z o.o.] Jak długo można czekać na odpowiedź księgowego, zanim stanie się to problemem dla firmy?', 'pomysl', ''),
  ('linkedin-topic-33', 'linkedin', 'Problemy', '[Sp. z o.o.] Dlaczego informacja o wysokości podatku przekazana tuż przed terminem płatności jest problemem zarządczym?', 'pomysl', ''),
  ('linkedin-topic-34', 'linkedin', 'Problemy', '[Sp. z o.o.] Co zrobić, jeżeli zarząd dostaje deklaracje podatkowe, ale nadal nie wie, co rzeczywiście dzieje się w finansach firmy?', 'pomysl', ''),
  ('linkedin-topic-35', 'linkedin', 'Problemy', '[Sp. z o.o.] Jak rozpoznać źle zorganizowany obieg dokumentów między spółką a biurem rachunkowym?', 'pomysl', ''),
  ('linkedin-topic-36', 'linkedin', 'Problemy', '[Sp. z o.o.] Co oznacza sytuacja, w której saldo banku, rozrachunki i księgi nie dają zarządowi spójnego obrazu?', 'pomysl', ''),
  ('linkedin-topic-37', 'linkedin', 'Problemy', '[Sp. z o.o.] Dlaczego nieuzgodnione należności i zobowiązania mogą być większym problemem niż sam podatek?', 'pomysl', ''),
  ('linkedin-topic-38', 'linkedin', 'Problemy', '[Sp. z o.o.] Co zrobić, jeżeli nowe biuro podczas przejęcia ksiąg znajduje błędy z poprzednich miesięcy?', 'pomysl', ''),
  ('linkedin-topic-39', 'linkedin', 'Problemy', '[Sp. z o.o.] Jak zarząd może sprawdzić, czy wszystkie deklaracje i obowiązki zostały wykonane na czas?', 'pomysl', ''),
  ('linkedin-topic-40', 'linkedin', 'Problemy', '[Sp. z o.o.] Po czym poznać, że spółka wyrosła z dotychczasowego sposobu prowadzenia księgowości?', 'pomysl', ''),
  ('linkedin-topic-41', 'linkedin', 'Problemy', '[Sp. z o.o.] Jakie problemy najczęściej pojawiają się, gdy spółka zaczyna sprzedawać lub kupować za granicą?', 'pomysl', ''),
  ('linkedin-topic-42', 'linkedin', 'Problemy', '[Sp. z o.o.] Dlaczego księgowość sklepu internetowego zaczyna się komplikować wraz ze wzrostem sprzedaży?', 'pomysl', ''),
  ('linkedin-topic-43', 'linkedin', 'Problemy', '[Sp. z o.o.] Co firma traci, gdy zamknięcie miesiąca trwa tak długo, że dane przestają być użyteczne?', 'pomysl', ''),
  ('linkedin-topic-44', 'linkedin', 'Problemy', '[Sp. z o.o.] Czy księgowość może pomóc ograniczyć sytuacje, w których właściciel jest zaskakiwany wysokością zobowiązań?', 'pomysl', ''),
  ('linkedin-topic-45', 'linkedin', 'Problemy', '[Sp. z o.o.] Co się dzieje, kiedy za obsługę klienta nie odpowiada jedna konkretna osoba?', 'pomysl', ''),
  ('linkedin-topic-46', 'linkedin', 'Problemy', '[Sp. z o.o.] Dlaczego standardowa księgowość nie zawsze dostarcza zarządowi danych potrzebnych do zarządzania?', 'pomysl', ''),
  ('linkedin-topic-47', 'linkedin', 'Problemy', '[NGO] Co może się stać, gdy księgowość nie rozdziela poprawnie działalności statutowej, odpłatnej i gospodarczej?', 'pomysl', ''),
  ('linkedin-topic-48', 'linkedin', 'Problemy', '[NGO] Dlaczego rozliczenie dotacji nie powinno zaczynać się dopiero przed terminem złożenia sprawozdania?', 'pomysl', ''),
  ('linkedin-topic-49', 'linkedin', 'Problemy', '[NGO] Jakie błędy księgowe mogą prowadzić do zakwestionowania części wydatków z dotacji?', 'pomysl', ''),
  ('linkedin-topic-50', 'linkedin', 'Problemy', '[NGO] Co zrobić, jeżeli organizacja zorientuje się po terminie, że nie złożyła wymaganego sprawozdania?', 'pomysl', ''),
  ('linkedin-topic-51', 'linkedin', 'Problemy', '[NGO] Po czym poznać, że UEPIK przestała odpowiadać skali i sposobowi działania organizacji?', 'pomysl', ''),
  ('linkedin-topic-52', 'linkedin', 'Problemy', '[Klub sportowy] Dlaczego pomylenie sponsoringu z darowizną może prowadzić do problemów podatkowych?', 'pomysl', ''),
  ('linkedin-topic-53', 'linkedin', 'Problemy', '[NGO] Jak prawidłowo uporządkować księgowość, gdy organizacja otrzymuje składki, darowizny, dotacje i wpływy z działalności odpłatnej?', 'pomysl', ''),
  ('linkedin-topic-54', 'linkedin', 'Problemy', '[Klub sportowy] Jak przygotować księgowość klubu do kontroli rozliczenia dotacji?', 'pomysl', ''),
  ('linkedin-topic-55', 'linkedin', 'Problemy', '[JDG] Jakie konsekwencje może mieć źle dobrana forma opodatkowania?', 'pomysl', ''),
  ('linkedin-topic-56', 'linkedin', 'Problemy', '[JDG] Jakie błędy najczęściej popełnia przedsiębiorca, który sam prowadzi księgowość?', 'pomysl', ''),
  ('linkedin-topic-57', 'linkedin', 'Problemy', '[JDG] Dlaczego wdrożenie KSeF nie rozwiązuje automatycznie problemu chaosu w dokumentach?', 'pomysl', ''),
  ('linkedin-topic-58', 'linkedin', 'Problemy', '[Wspólne] Co powinno się wydarzyć, kiedy księgowy prowadzący klienta idzie na urlop albo choruje?', 'pomysl', ''),
  ('linkedin-topic-59', 'linkedin', 'Problemy', '[Wspólne] Po czym poznać, że zakres umowy z biurem nie odpowiada już rzeczywistym potrzebom organizacji?', 'pomysl', ''),
  ('linkedin-topic-60', 'linkedin', 'Problemy', '[Wspólne] Dlaczego właściciel albo zarząd wciąż musi rozwiązywać problemy księgowe, skoro płaci za zewnętrzną obsługę?', 'pomysl', ''),
  ('linkedin-topic-61', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Własna księgowa czy zewnętrzne biuro rachunkowe – kiedy które rozwiązanie ma więcej sensu?', 'pomysl', ''),
  ('linkedin-topic-62', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Lokalne biuro rachunkowe czy księgowość całkowicie online – co naprawdę się różni?', 'pomysl', ''),
  ('linkedin-topic-63', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Dedykowana księgowa czy obsługa przez cały zespół – który model jest bezpieczniejszy?', 'pomysl', ''),
  ('linkedin-topic-64', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Tani pakiet księgowy czy szersza obsługa – za co właściwie płaci spółka?', 'pomysl', ''),
  ('linkedin-topic-65', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Sama księgowość podatkowa czy księgowość z miesięcznym raportowaniem dla zarządu?', 'pomysl', ''),
  ('linkedin-topic-66', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Biuro rachunkowe z dostępem do doradcy podatkowego czy zwykłe biuro księgowe?', 'pomysl', ''),
  ('linkedin-topic-67', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Przejęcie ksiąg z audytem startowym czy rozpoczęcie obsługi bez sprawdzania historii?', 'pomysl', ''),
  ('linkedin-topic-68', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Stały abonament czy rozliczenie zależne od liczby dokumentów – który model jest bardziej przewidywalny?', 'pomysl', ''),
  ('linkedin-topic-69', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Biuro specjalizujące się w e-commerce czy zwykłe biuro rachunkowe – kiedy specjalizacja ma znaczenie?', 'pomysl', ''),
  ('linkedin-topic-70', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Pełne zlecenie księgowości na zewnątrz czy pozostawienie części pracy administracyjnej wewnątrz firmy?', 'pomysl', ''),
  ('linkedin-topic-71', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Małe wyspecjalizowane biuro czy duża sieć księgowa – jakie są realne różnice?', 'pomysl', ''),
  ('linkedin-topic-72', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Dokumenty wysyłane mailem czy uporządkowany system obiegu dokumentów?', 'pomysl', ''),
  ('linkedin-topic-73', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o./JDG] Pełna księgowość spółki z o.o. a KPiR w JDG – co zmienia się z perspektywy właściciela?', 'pomysl', ''),
  ('linkedin-topic-74', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Klasyczny CIT czy estoński CIT – co zmienia się w księgowości i sposobie wypłacania pieniędzy?', 'pomysl', ''),
  ('linkedin-topic-75', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o./JDG] Pozostać na JDG czy przejść na spółkę z o.o. – jak zmieni się księgowość i jej koszt?', 'pomysl', ''),
  ('linkedin-topic-76', 'linkedin', 'Zestawienia i porównania', '[Sp. z o.o.] Biuro, które tylko księguje, czy biuro, które również porządkuje informacje dla zarządu?', 'pomysl', ''),
  ('linkedin-topic-77', 'linkedin', 'Zestawienia i porównania', '[NGO] UEPIK czy pełna księgowość – jakie są praktyczne różnice dla organizacji?', 'pomysl', ''),
  ('linkedin-topic-78', 'linkedin', 'Zestawienia i porównania', '[NGO] Księgowość prowadzona przez wolontariusza czy wyspecjalizowane biuro NGO?', 'pomysl', ''),
  ('linkedin-topic-79', 'linkedin', 'Zestawienia i porównania', '[NGO] Zwykłe biuro rachunkowe czy biuro specjalizujące się w fundacjach i stowarzyszeniach?', 'pomysl', ''),
  ('linkedin-topic-80', 'linkedin', 'Zestawienia i porównania', '[NGO] Jedno biuro do księgowości i rozliczania dotacji czy dwóch oddzielnych specjalistów?', 'pomysl', ''),
  ('linkedin-topic-81', 'linkedin', 'Zestawienia i porównania', '[Klub sportowy] Klub sportowy jako stowarzyszenie a klub działający w innej formie prawnej – co zmienia się w księgowości?', 'pomysl', ''),
  ('linkedin-topic-82', 'linkedin', 'Zestawienia i porównania', '[Klub sportowy] Sponsoring czy darowizna – czym różnią się podatkowo i dokumentacyjnie?', 'pomysl', ''),
  ('linkedin-topic-83', 'linkedin', 'Zestawienia i porównania', '[NGO] Organizacja ze statusem OPP i bez statusu OPP – jakie dodatkowe obowiązki pojawiają się w księgowości i sprawozdawczości?', 'pomysl', ''),
  ('linkedin-topic-84', 'linkedin', 'Zestawienia i porównania', '[NGO] Rozliczanie projektów w arkuszach kalkulacyjnych czy w dobrze ustawionym systemie księgowym?', 'pomysl', ''),
  ('linkedin-topic-85', 'linkedin', 'Zestawienia i porównania', '[JDG] Biuro rachunkowe czy aplikacja do samodzielnego księgowania?', 'pomysl', ''),
  ('linkedin-topic-86', 'linkedin', 'Zestawienia i porównania', '[JDG] Księgowość lokalna czy całkowicie zdalna?', 'pomysl', ''),
  ('linkedin-topic-87', 'linkedin', 'Zestawienia i porównania', '[JDG] Stała księgowa czy kontakt z infolinią dużego operatora księgowego?', 'pomysl', ''),
  ('linkedin-topic-88', 'linkedin', 'Zestawienia i porównania', '[JDG] Samodzielna księgowość czy outsourcing – kiedy oszczędność przestaje mieć sens?', 'pomysl', ''),
  ('linkedin-topic-89', 'linkedin', 'Zestawienia i porównania', '[Wspólne] Najtańsza usługa czy dostęp do człowieka, który odpowiada na pytania – co jest więcej warte?', 'pomysl', ''),
  ('linkedin-topic-90', 'linkedin', 'Zestawienia i porównania', '[Wspólne] Czy po zmianie formy działalności warto zostać z tym samym biurem, czy poszukać specjalisty od nowego rodzaju księgowości?', 'pomysl', ''),
  ('linkedin-topic-91', 'linkedin', 'Recenzje', '[Sp. z o.o.] Czy opinie w Google naprawdę pomagają wybrać biuro rachunkowe dla spółki?', 'pomysl', ''),
  ('linkedin-topic-92', 'linkedin', 'Recenzje', '[Sp. z o.o.] Na jakie informacje w opiniach klientów warto zwracać uwagę, a które są mało znaczące?', 'pomysl', ''),
  ('linkedin-topic-93', 'linkedin', 'Recenzje', '[Sp. z o.o.] Czy opinia właściciela podobnej spółki jest więcej warta niż ogólne „polecam”?', 'pomysl', ''),
  ('linkedin-topic-94', 'linkedin', 'Recenzje', '[Sp. z o.o.] Co mówi o biurze opinia klienta współpracującego z nim od pięciu albo dziesięciu lat?', 'pomysl', ''),
  ('linkedin-topic-95', 'linkedin', 'Recenzje', '[Sp. z o.o.] Jak interpretować powtarzające się negatywne opinie dotyczące kontaktu z księgową?', 'pomysl', ''),
  ('linkedin-topic-96', 'linkedin', 'Recenzje', '[Sp. z o.o.] Czy szybkość odpowiedzi pojawiająca się w recenzjach jest dobrym wskaźnikiem jakości biura?', 'pomysl', ''),
  ('linkedin-topic-97', 'linkedin', 'Recenzje', '[Sp. z o.o.] Jak sprawdzić w opiniach, czy klient rzeczywiście ma przypisaną konkretną osobę?', 'pomysl', ''),
  ('linkedin-topic-98', 'linkedin', 'Recenzje', '[Sp. z o.o.] Dlaczego klienci tak często chwalą księgowych za jasne tłumaczenie przepisów?', 'pomysl', ''),
  ('linkedin-topic-99', 'linkedin', 'Recenzje', '[Sp. z o.o.] Czy terminowość rozliczeń powinna być przewagą biura, czy jedynie podstawowym standardem?', 'pomysl', ''),
  ('linkedin-topic-100', 'linkedin', 'Recenzje', '[Sp. z o.o.] Jak rozpoznać w opiniach, czy biuro działa proaktywnie, czy tylko reaguje na pytania?', 'pomysl', ''),
  ('linkedin-topic-101', 'linkedin', 'Recenzje', '[Sp. z o.o.] Jak oceniać opinię klienta opisującego błąd księgowy i sposób, w jaki biuro go naprawiło?', 'pomysl', ''),
  ('linkedin-topic-102', 'linkedin', 'Recenzje', '[Sp. z o.o.] Czy dobrą oznaką jest sytuacja, gdy księgowy przyznaje, że czegoś nie wie i kieruje klienta do właściwego specjalisty?', 'pomysl', ''),
  ('linkedin-topic-103', 'linkedin', 'Recenzje', '[Sp. z o.o.] Jakich opinii szukać, jeżeli najbardziej obawiamy się samego procesu zmiany biura?', 'pomysl', ''),
  ('linkedin-topic-104', 'linkedin', 'Recenzje', '[Sp. z o.o.] Czy warto szukać opinii klientów, którzy przeszli z biurem kontrolę urzędu?', 'pomysl', ''),
  ('linkedin-topic-105', 'linkedin', 'Recenzje', '[Sp. z o.o.] Co opinie mogą powiedzieć o dodatkowych i nieprzewidzianych opłatach?', 'pomysl', ''),
  ('linkedin-topic-106', 'linkedin', 'Recenzje', '[Sp. z o.o.] Czy klienci rzeczywiście doceniają dostęp online do dokumentów i informacji finansowych?', 'pomysl', ''),
  ('linkedin-topic-107', 'linkedin', 'Recenzje', '[NGO] Jakie opinie powinno sprawdzać NGO przed wyborem biura rachunkowego?', 'pomysl', ''),
  ('linkedin-topic-108', 'linkedin', 'Recenzje', '[NGO] Czy warto szukać referencji organizacji, które rozliczały z danym biurem dotacje?', 'pomysl', ''),
  ('linkedin-topic-109', 'linkedin', 'Recenzje', '[NGO] Jak sprawdzić, czy biuro ma rzeczywiste doświadczenie ze sprawozdawczością NGO, a nie tylko deklaruje specjalizację?', 'pomysl', ''),
  ('linkedin-topic-110', 'linkedin', 'Recenzje', '[NGO] Jakie opinie powinny interesować organizację, która obawia się kontroli grantodawcy?', 'pomysl', ''),
  ('linkedin-topic-111', 'linkedin', 'Recenzje', '[Klub sportowy] Czy referencja innego klubu sportowego jest istotniejsza niż opinia zwykłej firmy?', 'pomysl', ''),
  ('linkedin-topic-112', 'linkedin', 'Recenzje', '[Klub sportowy] Jak sprawdzić, czy biuro zna w praktyce rozliczanie sponsorów, dotacji i składek?', 'pomysl', ''),
  ('linkedin-topic-113', 'linkedin', 'Recenzje', '[NGO] Czy rekomendacja innej fundacji jest ważniejsza niż liczba gwiazdek w Google?', 'pomysl', ''),
  ('linkedin-topic-114', 'linkedin', 'Recenzje', '[NGO] Jak oceniać biuro, które przejmowało księgowość po księgowej-wolontariuszu albo poprzednim nierzetelnym dostawcy?', 'pomysl', ''),
  ('linkedin-topic-115', 'linkedin', 'Recenzje', '[JDG] Jak czytać opinie o dużych internetowych biurach rachunkowych?', 'pomysl', ''),
  ('linkedin-topic-116', 'linkedin', 'Recenzje', '[JDG] Czy informacja, że klient od kilku lat ma tę samą księgową, jest istotna?', 'pomysl', ''),
  ('linkedin-topic-117', 'linkedin', 'Recenzje', '[JDG] Jak dużo mówi opinia klienta opisującego pomoc przy niestandardowej fakturze zagranicznej?', 'pomysl', ''),
  ('linkedin-topic-118', 'linkedin', 'Recenzje', '[Wspólne] Czy same pięciogwiazdkowe opinie powinny wzbudzać większe zaufanie?', 'pomysl', ''),
  ('linkedin-topic-119', 'linkedin', 'Recenzje', '[Wspólne] Gdzie poza Google warto sprawdzać wiarygodność biura rachunkowego?', 'pomysl', ''),
  ('linkedin-topic-120', 'linkedin', 'Recenzje', '[Wspólne] Co jest ważniejsze przy wyborze biura: liczba opinii czy ich konkretność?', 'pomysl', ''),
  ('linkedin-topic-121', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jak powinno wyglądać dobre biuro rachunkowe dla rozwijającej się spółki z o.o.?', 'pomysl', ''),
  ('linkedin-topic-122', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jak wybrać najlepszą księgowość dla spółki prowadzącej e-commerce?', 'pomysl', ''),
  ('linkedin-topic-123', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jakiego biura powinna szukać spółka mająca dużo transakcji zagranicznych?', 'pomysl', ''),
  ('linkedin-topic-124', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jak powinna wyglądać księgowość firmy z wieloma rachunkami, rozrachunkami i dużą liczbą płatności?', 'pomysl', ''),
  ('linkedin-topic-125', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jakiego biura powinna szukać spółka zatrudniająca coraz więcej pracowników?', 'pomysl', ''),
  ('linkedin-topic-126', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jak wybrać biuro, jeżeli zarząd oczekuje miesięcznych raportów i aktualnych danych?', 'pomysl', ''),
  ('linkedin-topic-127', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jakie biuro najlepiej poradzi sobie ze zmianą księgowości w trakcie roku?', 'pomysl', ''),
  ('linkedin-topic-128', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jakiego biura szukać, jeżeli podejrzewamy, że w dotychczasowych księgach są błędy?', 'pomysl', ''),
  ('linkedin-topic-129', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jak powinien wyglądać model obsługi, jeśli właściciel chce mieć jednego konkretnego opiekuna?', 'pomysl', ''),
  ('linkedin-topic-130', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jak powinno działać dobre biuro rachunkowe obsługujące klientów całkowicie online?', 'pomysl', ''),
  ('linkedin-topic-131', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Kiedy najlepszym wyborem będzie biuro posiadające stały dostęp do doradcy podatkowego?', 'pomysl', ''),
  ('linkedin-topic-132', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jak powinna wyglądać księgowość, która naprawdę ogranicza zaangażowanie właściciela?', 'pomysl', ''),
  ('linkedin-topic-133', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jaki czas odpowiedzi powinien być standardem w dobrym biurze rachunkowym?', 'pomysl', ''),
  ('linkedin-topic-134', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Po jakich mierzalnych cechach można poznać dobrze zorganizowane biuro?', 'pomysl', ''),
  ('linkedin-topic-135', 'linkedin', 'Najlepsze w swojej klasie', '[Sp. z o.o.] Jakiego modelu księgowości powinien szukać właściciel, który nie zna się na finansach?', 'pomysl', ''),
  ('linkedin-topic-136', 'linkedin', 'Najlepsze w swojej klasie', '[NGO] Jak powinno wyglądać dobre biuro rachunkowe dla fundacji korzystającej z dotacji?', 'pomysl', ''),
  ('linkedin-topic-137', 'linkedin', 'Najlepsze w swojej klasie', '[NGO] Jakiego biura powinna szukać organizacja mająca status OPP?', 'pomysl', ''),
  ('linkedin-topic-138', 'linkedin', 'Najlepsze w swojej klasie', '[NGO] Jak powinna wyglądać księgowość organizacji realizującej równocześnie kilka projektów?', 'pomysl', ''),
  ('linkedin-topic-139', 'linkedin', 'Najlepsze w swojej klasie', '[NGO] Jak wybrać księgowość dla organizacji realizującej projekty finansowane ze środków publicznych lub europejskich?', 'pomysl', ''),
  ('linkedin-topic-140', 'linkedin', 'Najlepsze w swojej klasie', '[Klub sportowy] Jakiego biura rachunkowego powinien szukać duży klub korzystający z dotacji samorządowych?', 'pomysl', ''),
  ('linkedin-topic-141', 'linkedin', 'Najlepsze w swojej klasie', '[Klub sportowy] Jak powinna wyglądać księgowość klubu współpracującego z wieloma sponsorami?', 'pomysl', ''),
  ('linkedin-topic-142', 'linkedin', 'Najlepsze w swojej klasie', '[NGO] Jakiego biura powinna szukać organizacja, która przestaje być małą inicjatywą opartą na wolontariacie?', 'pomysl', ''),
  ('linkedin-topic-143', 'linkedin', 'Najlepsze w swojej klasie', '[NGO] Po czym poznać, że dla organizacji najlepsza będzie już pełna księgowość zamiast UEPIK?', 'pomysl', ''),
  ('linkedin-topic-144', 'linkedin', 'Najlepsze w swojej klasie', '[NGO] Jak powinien wyglądać dobry obieg dokumentów w fundacji albo stowarzyszeniu?', 'pomysl', ''),
  ('linkedin-topic-145', 'linkedin', 'Najlepsze w swojej klasie', '[JDG] Jakiego księgowego powinien szukać przedsiębiorca dopiero zakładający działalność?', 'pomysl', ''),
  ('linkedin-topic-146', 'linkedin', 'Najlepsze w swojej klasie', '[JDG] Jak powinna wyglądać dobra obsługa księgowa JDG będącej podatnikiem VAT?', 'pomysl', ''),
  ('linkedin-topic-147', 'linkedin', 'Najlepsze w swojej klasie', '[JDG] Jakiej księgowości potrzebuje JDG współpracująca głównie z klientami zagranicznymi?', 'pomysl', ''),
  ('linkedin-topic-148', 'linkedin', 'Najlepsze w swojej klasie', '[JDG] Kiedy najlepsza będzie aplikacja księgowa, a kiedy człowiek?', 'pomysl', ''),
  ('linkedin-topic-149', 'linkedin', 'Najlepsze w swojej klasie', '[Wspólne] Jakie informacje finansowe dobry księgowy powinien regularnie przekazywać właścicielowi albo zarządowi?', 'pomysl', ''),
  ('linkedin-topic-150', 'linkedin', 'Najlepsze w swojej klasie', '[Wspólne] Jakie pytania trzeba zadać biuru rachunkowemu przed podpisaniem umowy, żeby wybrać właściwe?', 'pomysl', ''),
  ('linkedin-topic-151', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Czy można bezpiecznie zmienić biuro rachunkowe w środku roku?', 'pomysl', ''),
  ('linkedin-topic-152', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Co zrobić, jeżeli poprzednie biuro nie chce sprawnie przekazać dokumentów?', 'pomysl', ''),
  ('linkedin-topic-153', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Kto odpowiada za błędy popełnione przez poprzednią księgowość?', 'pomysl', ''),
  ('linkedin-topic-154', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Czy nowe biuro powinno sprawdzić księgi przed rozpoczęciem normalnej obsługi?', 'pomysl', ''),
  ('linkedin-topic-155', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Czy lepiej zmieniać biuro od stycznia, czy termin nie ma aż takiego znaczenia?', 'pomysl', ''),
  ('linkedin-topic-156', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Ile czasu trwa bezpieczne przejęcie księgowości spółki?', 'pomysl', ''),
  ('linkedin-topic-157', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Czy nowe biuro może samo kontaktować się z dotychczasowym księgowym i przejąć większość procesu?', 'pomysl', ''),
  ('linkedin-topic-158', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Ile pracy po stronie zarządu wymaga zmiana biura rachunkowego?', 'pomysl', ''),
  ('linkedin-topic-159', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Czy księgowość całkowicie online jest bezpieczna dla dokumentów i danych finansowych spółki?', 'pomysl', ''),
  ('linkedin-topic-160', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Kto w biurze rachunkowym powinien mieć dostęp do danych naszej firmy?', 'pomysl', ''),
  ('linkedin-topic-161', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Co dzieje się z obsługą spółki, kiedy dedykowana księgowa jest na urlopie?', 'pomysl', ''),
  ('linkedin-topic-162', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Czy biuro rachunkowe może zagwarantować określony czas odpowiedzi?', 'pomysl', ''),
  ('linkedin-topic-163', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Skąd wiadomo, że biuro poradzi sobie, jeżeli firma w ciągu roku podwoi skalę działalności?', 'pomysl', ''),
  ('linkedin-topic-164', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Czy biuro rachunkowe reprezentuje klienta podczas kontroli urzędu?', 'pomysl', ''),
  ('linkedin-topic-165', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Za co odpowiada biuro rachunkowe, a za co nadal odpowiada zarząd spółki?', 'pomysl', ''),
  ('linkedin-topic-166', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Czy nowe biuro przyjmie spółkę, jeżeli księgi są nieuporządkowane?', 'pomysl', ''),
  ('linkedin-topic-167', 'linkedin', 'Inne i obawy', '[Sp. z o.o.] Co zrobić, gdy części dokumentów z poprzednich miesięcy po prostu brakuje?', 'pomysl', ''),
  ('linkedin-topic-168', 'linkedin', 'Inne i obawy', '[NGO] Czy można zmienić księgowość w trakcie realizacji dotowanego projektu?', 'pomysl', ''),
  ('linkedin-topic-169', 'linkedin', 'Inne i obawy', '[NGO] Skąd mieć pewność, że nowe biuro zrozumie wymagania konkretnego grantodawcy?', 'pomysl', ''),
  ('linkedin-topic-170', 'linkedin', 'Inne i obawy', '[NGO] Co zrobić, gdy po zmianie księgowości okazuje się, że wcześniejsze wydatki z dotacji zostały źle zaksięgowane?', 'pomysl', ''),
  ('linkedin-topic-171', 'linkedin', 'Inne i obawy', '[NGO] Czy można przejść z UEPIK na pełne księgi i kiedy najlepiej to zrobić?', 'pomysl', ''),
  ('linkedin-topic-172', 'linkedin', 'Inne i obawy', '[NGO] Co grozi organizacji, jeśli sprawozdanie albo deklaracja zostały złożone po terminie?', 'pomysl', ''),
  ('linkedin-topic-173', 'linkedin', 'Inne i obawy', '[Klub sportowy] Jak odróżnić i prawidłowo udokumentować wpływy od sponsorów, darowizny i dotacje?', 'pomysl', ''),
  ('linkedin-topic-174', 'linkedin', 'Inne i obawy', '[Klub sportowy] Jak przechowywać dokumentację projektu, żeby później nie mieć problemu przy kontroli dotacji?', 'pomysl', ''),
  ('linkedin-topic-175', 'linkedin', 'Inne i obawy', '[JDG] Czy mała działalność rzeczywiście potrzebuje księgowej?', 'pomysl', ''),
  ('linkedin-topic-176', 'linkedin', 'Inne i obawy', '[JDG] Czy w okresie zmian związanych z KSeF warto zmieniać księgowość?', 'pomysl', ''),
  ('linkedin-topic-177', 'linkedin', 'Inne i obawy', '[JDG] Czy przesyłanie wszystkich dokumentów przez internet jest bezpieczne?', 'pomysl', ''),
  ('linkedin-topic-178', 'linkedin', 'Inne i obawy', '[JDG] Dlaczego mam płacić kilkaset złotych za biuro, skoro program księgowy kosztuje kilkadziesiąt?', 'pomysl', ''),
  ('linkedin-topic-179', 'linkedin', 'Inne i obawy', '[Wspólne] Czy mogę zadzwonić do księgowego z pojedynczym pytaniem, czy każda dodatkowa konsultacja będzie płatna?', 'pomysl', ''),
  ('linkedin-topic-180', 'linkedin', 'Inne i obawy', '[Wspólne] Jak przed podpisaniem umowy sprawdzić, czy komunikacja z biurem rzeczywiście będzie wyglądała tak dobrze, jak obiecuje sprzedawca?', 'pomysl', '')
on conflict (id) do nothing;
